################################################################################
#   SECTION: Capabilities
################################################################################
Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_0: true

################################################################################
#   CHANNEL Defaults
################################################################################
Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

################################################################################
#   Section: Organizations
################################################################################
Organizations:
    - &Orderer
      Name: OrdererMSP
      ID: OrdererMSP
      MSPDir: crypto-config/peerOrganizations/root.com/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('OrdererMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('OrdererMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('OrdererMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('OrdererMSP.member')"

      AnchorPeers:

    - &FarmerOrg
      Name: FarmerOrgMSP
      ID: FarmerOrgMSP
      MSPDir: crypto-config/peerOrganizations/farmer.example.com/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('FarmerOrgMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('FarmerOrgMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('FarmerOrgMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('FarmerOrgMSP.member')"

      AnchorPeers:
          - Host: peer0.farmer.example.com
            Port: 7041

          - Host: peer1.farmer.example.com
            Port: 7042

    - &AuditorOrg
      Name: AuditorOrgMSP
      ID: AuditorOrgMSP
      MSPDir: crypto-config/peerOrganizations/auditor.example.com/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('AuditorOrgMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('AuditorOrgMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('AuditorOrgMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('AuditorOrgMSP.member')"

      AnchorPeers:
          - Host: peer0.auditor.example.com
            Port: 7061

          - Host: peer1.auditor.example.com
            Port: 7062

    - &TransporterOrg
      Name: TransporterOrgMSP
      ID: TransporterOrgMSP
      MSPDir: crypto-config/peerOrganizations/transporter.example.com/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('TransporterOrgMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('TransporterOrgMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('TransporterOrgMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('TransporterOrgMSP.member')"

      AnchorPeers:
          - Host: peer0.transporter.example.com
            Port: 7081

          - Host: peer1.transporter.example.com
            Port: 7082

################################################################################
#   SECTION: Application
################################################################################
Application: &ApplicationDefaults
    Organizations:
    # Policies defines the set of policies at this level of the config tree
    # For Application policies, their canonical path is
    #   /Channel/Application/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
    Capabilities:
        <<: *ApplicationCapabilities

################################################################################
#   SECTION: Orderer
################################################################################
Orderer: &Group1Defaults
    OrdererType: solo
    Addresses:
        - orderer0.group1.root.com:7030
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:
    # Policies defines the set of policies at this level of the config tree
    # For Orderer policies, their canonical path is
    #   /Channel/Orderer/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        # BlockValidation specifies what signatures must be included in the block
        # from the orderer for the peer to validate it.
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"
    Capabilities:
        <<: *OrdererCapabilities

################################################################################
#   Profile
################################################################################
# https://github:com/hyperledger/fabric/blob/master/sampleconfig/configtx.yaml

Profiles:
    # Profile used to create Genesis block for group group1 #
    Group1Genesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *Group1Defaults
            Organizations:
                - *Orderer
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Orderer
                    - *FarmerOrg
                    - *AuditorOrg
                    - *TransporterOrg

    # Profile used to create channeltx for mychannel #
    Mychannel:
        <<: *ChannelDefaults
        Orderer:
            <<: *Group1Defaults
            Organizations:
                - *Orderer
            Capabilities:
                <<: *ApplicationCapabilities
        Consortium: SampleConsortium
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *FarmerOrg
                    - *AuditorOrg
                    - *TransporterOrg
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *FarmerOrg
                - *AuditorOrg
                - *TransporterOrg
