global:
  fabricVersion: 2.3.0
  tls: true
orgs:
  - organization:
      name: Orderer
      domain: root.com
    orderers:
      - groupName: group1
        prefix: orderer
        type: solo
        instances: 1 
  - organization:
      name: Farmer
      domain: farmer.example.com
      tools:
        fabloRest: true
        explorer: true
    peer:
      instances: 2
  - organization:
      name: Auditor
      domain: auditor.example.com
      tools:
        fabloRest: true
        explorer: true
    peer:
      instances: 2
  - organization:
      name: Transporter
      domain: transporter.example.com
      tools:
        fabloRest: true
        explorer: true
    peer:
      instances: 2
channels:
  - name: agridata
    orgs:
      - name: Farmer
        peers:
          - peer0
          - peer1
      - name: Auditor
        peers:
          - peer0
          - peer1
      - name: Transporter
        peers:
          - peer0
          - peer1
chaincodes:
  - name: trackmeat
    version: 0.0.1
    lang: golang
    channel: agridata
    directory: "../trackmeat"
    endorsement: AND('FarmerMSP.member', 'AuditorMSP.member', 'TransporterMSP.member')