global:
  fabricVersion: 2.3.0
  tls: true
orgs:
  - organization:
      name: Orderer
      domain: root.com
    orderers:
      - groupName: group1
        prefix: orderer
        type: solo
        instances: 1 
  - organization:
      name: FarmerOrg
      domain: farmer.example.com
      tools:
        fabloRest: true
        explorer: true
    peer:
      instances: 2
  - organization:
      name: AuditorOrg
      domain: auditor.example.com
      tools:
        fabloRest: true
        explorer: true
    peer:
      instances: 2
  - organization:
      name: TransporterOrg
      domain: transporter.example.com
      tools:
        fabloRest: true
        explorer: true
    peer:
      instances: 2
channels:
  - name: mychannel
    orgs:
      - name: FarmerOrg
        peers:
          - peer0
          - peer1
      - name: AuditorOrg
        peers:
          - peer0
          - peer1
      - name: TransporterOrg
        peers:
          - peer0
          - peer1
chaincodes:
  - name: and-policy-chaincode
    version: 0.0.1
    lang: golang
    channel: mychannel
    directory: "../trackmeat"